import { scoreLoadAgainstTrucks } from "./tamp-matching";
import type {
  AuditEvent,
  Dispute,
  Load,
  Match,
  Money,
  Party,
  Place,
  Rating,
  Trip,
  TruckPosting,
} from "./tamp-types";

export type PlaceKey =
  | "johannesburg"
  | "durban"
  | "capeTown"
  | "gqeberha"
  | "pretoria"
  | "musina"
  | "rustenburg"
  | "richardsBay"
  | "bloemfontein"
  | "kimberley"
  | "alberton"
  | "germiston"
  | "bellville"
  | "pretoriaNorth";

export const PLACES: Record<PlaceKey, Place> = {
  johannesburg: { label: "Johannesburg", province: "GP", lat: -26.2041, lng: 28.0473 },
  durban: { label: "Durban", province: "KZN", lat: -29.8587, lng: 31.0218 },
  capeTown: { label: "Cape Town", province: "WC", lat: -33.9249, lng: 18.4241 },
  gqeberha: { label: "Gqeberha", province: "EC", lat: -33.9608, lng: 25.6022 },
  pretoria: { label: "Pretoria", province: "GP", lat: -25.7479, lng: 28.2293 },
  musina: { label: "Musina", province: "LP", lat: -22.3285, lng: 30.0454 },
  rustenburg: { label: "Rustenburg", province: "NW", lat: -25.6672, lng: 27.2424 },
  richardsBay: { label: "Richards Bay", province: "KZN", lat: -28.7807, lng: 32.0383 },
  bloemfontein: { label: "Bloemfontein", province: "FS", lat: -29.0852, lng: 26.1596 },
  kimberley: { label: "Kimberley", province: "NC", lat: -28.7282, lng: 24.7499 },
  alberton: { label: "Alberton", province: "GP", lat: -26.2679, lng: 28.1222 },
  germiston: { label: "Germiston", province: "GP", lat: -26.2309, lng: 28.1751 },
  bellville: { label: "Bellville", province: "WC", lat: -33.8994, lng: 18.6292 },
  pretoriaNorth: { label: "Pretoria North", province: "GP", lat: -25.6541, lng: 28.1897 },
};

export const zar = (n: number) =>
  "R " + n.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const formatMoney = (m: Money) =>
  `${zar(m.amount)} ${m.vat === "incl" ? "incl. VAT" : "excl. VAT"}`;

const now = () => new Date().toISOString();
const daysFromNow = (d: number) => new Date(Date.now() + d * 864e5).toISOString();

export const seedParties: Party[] = [
  // Freight owners
  {
    id: "P-OWNER-1",
    role: "FREIGHT_OWNER",
    companyName: "Highveld Logistics (Pty) Ltd",
    contactName: "Nomvula Khumalo",
    email: "n.khumalo@highveldlog.co.za",
    phone: "082 111 2233",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: 4.5,
    ratingCount: 6,
    suspended: false,
    createdAt: daysFromNow(-90),
  },
  {
    id: "P-OWNER-2",
    role: "FREIGHT_OWNER",
    companyName: "Cape Bulk Minerals",
    contactName: "Johan Pretorius",
    email: "j.pretorius@capebulk.co.za",
    phone: "083 222 3344",
    province: "WC",
    verification: "VERIFIED",
    ratingAvg: 4.2,
    ratingCount: 4,
    suspended: false,
    createdAt: daysFromNow(-75),
  },
  {
    id: "P-OWNER-3",
    role: "FREIGHT_OWNER",
    companyName: "Tshwane Structural Steel",
    contactName: "Karabo Sekgota",
    email: "k.sekgota@tshwanesteel.co.za",
    phone: "084 333 4455",
    province: "GP",
    verification: "PENDING",
    ratingAvg: null,
    ratingCount: 0,
    suspended: false,
    createdAt: daysFromNow(-10),
  },
  {
    id: "P-OWNER-4",
    role: "FREIGHT_OWNER",
    companyName: "Bojanala Mining Supply",
    contactName: "Tebogo Modise",
    email: "t.modise@bojanala.co.za",
    phone: "071 444 5566",
    province: "NW",
    verification: "VERIFIED",
    ratingAvg: 4.8,
    ratingCount: 9,
    suspended: false,
    createdAt: daysFromNow(-120),
  },
  {
    id: "P-OWNER-5",
    role: "FREIGHT_OWNER",
    companyName: "Mangaung Cold Foods",
    contactName: "Elna van Wyk",
    email: "e.vanwyk@mangaungcold.co.za",
    phone: "072 555 6677",
    province: "FS",
    verification: "VERIFIED",
    ratingAvg: 3.6,
    ratingCount: 5,
    suspended: false,
    createdAt: daysFromNow(-60),
  },
  // Transporters
  {
    id: "P-TRANS-1",
    role: "TRANSPORTER",
    companyName: "Titan Heavy Haulage",
    contactName: "Sipho Ndlovu",
    email: "s.ndlovu@titanhaulage.co.za",
    phone: "082 666 7788",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: 4.9,
    ratingCount: 22,
    suspended: false,
    createdAt: daysFromNow(-200),
  },
  {
    id: "P-TRANS-2",
    role: "TRANSPORTER",
    companyName: "Zulu Transporters",
    contactName: "Bongani Zulu",
    email: "b.zulu@zulutrans.co.za",
    phone: "083 777 8899",
    province: "NW",
    verification: "VERIFIED",
    ratingAvg: 4.6,
    ratingCount: 15,
    suspended: false,
    createdAt: daysFromNow(-150),
  },
  {
    id: "P-TRANS-3",
    role: "TRANSPORTER",
    companyName: "Limpopo Linehaul",
    contactName: "Rendani Mulaudzi",
    email: "r.mulaudzi@limpopolinehaul.co.za",
    phone: "084 888 9900",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: 4.4,
    ratingCount: 11,
    suspended: false,
    createdAt: daysFromNow(-100),
  },
  {
    id: "P-TRANS-4",
    role: "TRANSPORTER",
    companyName: "Karoo Cold Chain",
    contactName: "Willem Botha",
    email: "w.botha@karoocold.co.za",
    phone: "071 999 0011",
    province: "FS",
    verification: "PENDING",
    ratingAvg: 3.9,
    ratingCount: 3,
    suspended: false,
    createdAt: daysFromNow(-20),
  },
  {
    id: "P-TRANS-5",
    role: "TRANSPORTER",
    companyName: "Boland Freight Co-op",
    contactName: "Anele Dlamini",
    email: "a.dlamini@bolandfreight.co.za",
    phone: "072 000 1122",
    province: "WC",
    verification: "VERIFIED",
    ratingAvg: 4.7,
    ratingCount: 18,
    suspended: false,
    createdAt: daysFromNow(-180),
  },
  {
    id: "P-TRANS-6",
    role: "TRANSPORTER",
    companyName: "N3 Owner-Driver Group",
    contactName: "Given Mahlangu",
    email: "g.mahlangu@n3odg.co.za",
    phone: "073 111 2233",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: 4.2,
    ratingCount: 7,
    suspended: false,
    createdAt: daysFromNow(-40),
  },
  // Truck drivers (companyName = their employer, for display)
  {
    id: "P-DRIVER-1",
    role: "DRIVER",
    companyName: "Limpopo Linehaul",
    contactName: "Thabo Mokoena",
    email: "t.mokoena@limpopolinehaul.co.za",
    phone: "082 345 6677",
    province: "LP",
    verification: "VERIFIED",
    ratingAvg: 4.7,
    ratingCount: 31,
    suspended: false,
    createdAt: daysFromNow(-140),
  },
  {
    id: "P-DRIVER-2",
    role: "DRIVER",
    companyName: "Titan Heavy Haulage",
    contactName: "Pieter van der Merwe",
    email: "p.vdmerwe@titanhaulage.co.za",
    phone: "083 456 7788",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: 4.9,
    ratingCount: 44,
    suspended: false,
    createdAt: daysFromNow(-260),
  },
  {
    id: "P-DRIVER-3",
    role: "DRIVER",
    companyName: "Zulu Transporters",
    contactName: "Lerato Molefe",
    email: "l.molefe@zulutrans.co.za",
    phone: "084 567 8899",
    province: "NW",
    verification: "PENDING",
    ratingAvg: 4.3,
    ratingCount: 12,
    suspended: false,
    createdAt: daysFromNow(-55),
  },
  // Admin
  {
    id: "P-ADMIN-1",
    role: "ADMIN",
    companyName: "Industrial Computing Engineering (Pty) Ltd",
    contactName: "TAMP Platform Admin",
    email: "admin@tamp.co.za",
    phone: "010 000 0000",
    province: "GP",
    verification: "VERIFIED",
    ratingAvg: null,
    ratingCount: 0,
    suspended: false,
    createdAt: daysFromNow(-365),
  },
];

const money = (amount: number, vat: "incl" | "excl" = "excl"): Money => ({
  amount,
  currency: "ZAR",
  vat,
});

export const seedLoads: Load[] = [
  {
    id: "LD-0142",
    ownerId: "P-OWNER-1",
    reference: "LD-0142",
    cargoType: "GENERAL_PALLETISED",
    weightKg: 24000,
    requiredBodyTypes: ["TAUTLINER"],
    origin: PLACES.johannesburg,
    destination: PLACES.durban,
    distanceKm: 620,
    pickupWindow: { from: daysFromNow(3), to: daysFromNow(4) },
    deliveryBy: daysFromNow(6),
    targetRate: money(18400),
    specialRequirements: "FMCG pallets, tail-lift preferred.",
    status: "POSTED",
    createdAt: daysFromNow(-2),
  },
  {
    id: "LD-0143",
    ownerId: "P-OWNER-2",
    reference: "LD-0143",
    cargoType: "BULK_DRY",
    weightKg: 34000,
    requiredBodyTypes: ["SIDE_TIPPER", "TIPPER"],
    origin: PLACES.capeTown,
    destination: PLACES.gqeberha,
    distanceKm: 770,
    pickupWindow: { from: daysFromNow(2), to: daysFromNow(3) },
    deliveryBy: daysFromNow(5),
    targetRate: money(32150),
    status: "POSTED",
    createdAt: daysFromNow(-3),
  },
  {
    id: "LD-0144",
    ownerId: "P-OWNER-3",
    reference: "LD-0144",
    cargoType: "ABNORMAL",
    weightKg: 28000,
    requiredBodyTypes: ["FLATBED", "LOWBED"],
    origin: PLACES.pretoria,
    destination: PLACES.musina,
    distanceKm: 500,
    pickupWindow: { from: daysFromNow(-1), to: daysFromNow(0) },
    deliveryBy: daysFromNow(3),
    targetRate: money(22000),
    status: "CONFIRMED",
    createdAt: daysFromNow(-6),
  },
  {
    id: "LD-0145",
    ownerId: "P-OWNER-4",
    reference: "LD-0145",
    cargoType: "BULK_DRY",
    weightKg: 34000,
    requiredBodyTypes: ["SIDE_TIPPER"],
    origin: PLACES.rustenburg,
    destination: PLACES.richardsBay,
    distanceKm: 780,
    pickupWindow: { from: daysFromNow(-6), to: daysFromNow(-5) },
    deliveryBy: daysFromNow(-2),
    targetRate: money(28750),
    status: "COMPLETED",
    createdAt: daysFromNow(-9),
  },
  {
    id: "LD-0146",
    ownerId: "P-OWNER-5",
    reference: "LD-0146",
    cargoType: "REFRIGERATED",
    weightKg: 18000,
    requiredBodyTypes: ["REFRIGERATED"],
    origin: PLACES.bloemfontein,
    destination: PLACES.kimberley,
    distanceKm: 180,
    pickupWindow: { from: daysFromNow(-8), to: daysFromNow(-7) },
    deliveryBy: daysFromNow(-4),
    targetRate: money(14300),
    status: "COMPLETED",
    createdAt: daysFromNow(-11),
  },
];

export const seedTrucks: TruckPosting[] = [
  {
    id: "TR-4401",
    transporterId: "P-TRANS-1",
    driverId: "P-DRIVER-2",
    registration: "JH 41 SG GP",
    bodyType: "TAUTLINER",
    payloadCapacityKg: 30000,
    currentLocation: PLACES.alberton,
    availableFrom: daysFromNow(2),
    availableTo: daysFromNow(10),
    preferredLanes: [{ origin: "Johannesburg", destination: "Durban" }],
    status: "AVAILABLE",
    createdAt: daysFromNow(-5),
  },
  {
    id: "TR-4402",
    transporterId: "P-TRANS-2",
    driverId: "P-DRIVER-3",
    registration: "ND 88 210",
    bodyType: "SIDE_TIPPER",
    payloadCapacityKg: 36000,
    currentLocation: PLACES.rustenburg,
    availableFrom: daysFromNow(1),
    availableTo: daysFromNow(8),
    preferredLanes: [{ origin: "Rustenburg", destination: "Richards Bay" }],
    status: "AVAILABLE",
    createdAt: daysFromNow(-8),
  },
  {
    id: "TR-4403",
    transporterId: "P-TRANS-2",
    registration: "ND 91 004",
    bodyType: "TIPPER",
    payloadCapacityKg: 32000,
    currentLocation: PLACES.capeTown,
    availableFrom: daysFromNow(1),
    availableTo: daysFromNow(6),
    status: "AVAILABLE",
    createdAt: daysFromNow(-4),
  },
  {
    id: "TR-4409",
    transporterId: "P-TRANS-2",
    registration: "ND 12 559",
    bodyType: "SIDE_TIPPER",
    payloadCapacityKg: 33500,
    currentLocation: PLACES.capeTown,
    availableFrom: daysFromNow(1),
    availableTo: daysFromNow(6),
    status: "AVAILABLE",
    createdAt: daysFromNow(-4),
  },
  {
    id: "TR-4410",
    transporterId: "P-TRANS-3",
    driverId: "P-DRIVER-1",
    registration: "BP 77 LP",
    bodyType: "FLATBED",
    payloadCapacityKg: 30000,
    currentLocation: PLACES.pretoriaNorth,
    availableFrom: daysFromNow(-2),
    availableTo: daysFromNow(4),
    status: "RESERVED",
    createdAt: daysFromNow(-7),
  },
  {
    id: "TR-4415",
    transporterId: "P-TRANS-4",
    registration: "FS 55 901",
    bodyType: "REFRIGERATED",
    payloadCapacityKg: 20000,
    currentLocation: PLACES.bloemfontein,
    availableFrom: daysFromNow(-9),
    availableTo: daysFromNow(-3),
    status: "AVAILABLE",
    createdAt: daysFromNow(-10),
  },
  {
    id: "TR-4422",
    transporterId: "P-TRANS-5",
    registration: "CA 902 331",
    bodyType: "SIDE_TIPPER",
    payloadCapacityKg: 38000,
    currentLocation: PLACES.bellville,
    availableFrom: daysFromNow(2),
    availableTo: daysFromNow(9),
    status: "AVAILABLE",
    createdAt: daysFromNow(-6),
  },
  {
    id: "TR-4430",
    transporterId: "P-TRANS-6",
    registration: "GP 12 884",
    bodyType: "TAUTLINER",
    payloadCapacityKg: 34000,
    currentLocation: PLACES.germiston,
    availableFrom: daysFromNow(2),
    availableTo: daysFromNow(7),
    status: "AVAILABLE",
    createdAt: daysFromNow(-3),
  },
];

const owner = (id: string) => seedParties.find((p) => p.id === id)!;

function generateMatches(loads: Load[], trucks: TruckPosting[]): Match[] {
  const matches: Match[] = [];
  let n = 300;
  for (const load of loads) {
    if (load.status !== "POSTED") continue;
    const ownerParty = owner(load.ownerId);
    const scored = scoreLoadAgainstTrucks(load, trucks, seedParties, ownerParty).filter(
      (m) => m.passed,
    );
    for (const m of scored) {
      matches.push({
        id: `MT-0${n++}`,
        loadId: load.id,
        truckPostingId: m.truck.id,
        score: m.score,
        breakdown: m.breakdown,
        hardFilterResults: m.hardFilterResults,
        status: "SUGGESTED",
        initiatedBy: "SYSTEM",
        // Long window so a seeded demo that sits idle isn't auto-expired by the
        // scheduler (server/scheduler.ts now enforces Match.expiresAt).
        expiresAt: daysFromNow(30),
        createdAt: now(),
      });
    }
  }
  return matches;
}

export const seedMatches: Match[] = [
  {
    id: "MT-0311",
    loadId: "LD-0144",
    truckPostingId: "TR-4410",
    score: 88,
    breakdown: [],
    hardFilterResults: [],
    status: "CONFIRMED",
    initiatedBy: "FREIGHT_OWNER",
    agreedRate: money(22000),
    confirmedByOwnerAt: daysFromNow(-1),
    confirmedByTransporterAt: daysFromNow(-1),
    expiresAt: daysFromNow(1),
    createdAt: daysFromNow(-2),
  },
  ...generateMatches(seedLoads, seedTrucks),
];

export const seedTrips: Trip[] = [
  {
    id: "TP-0058",
    matchId: "MT-0311",
    status: "IN_TRANSIT",
    disputed: false,
    events: [
      { status: "SCHEDULED", at: daysFromNow(-1), byUserId: "P-OWNER-3" },
      { status: "AT_PICKUP", at: daysFromNow(-1), byUserId: "P-TRANS-3" },
      { status: "LOADED", at: daysFromNow(-1), byUserId: "P-TRANS-3" },
      { status: "IN_TRANSIT", at: daysFromNow(0), byUserId: "P-TRANS-3" },
    ],
    simulatedPosition: { lat: -25.4, lng: 28.3, updatedAt: now() },
    progressPct: 45,
    etaAt: daysFromNow(2),
  },
];

export const seedRatings: Rating[] = [];

export const seedDisputes: Dispute[] = [];

export const seedAudit: AuditEvent[] = [
  {
    id: "EV-1004",
    eventId: "EVT-10",
    eventType: "LOAD_POSTED",
    actorId: "P-OWNER-1",
    actorRole: "FREIGHT_OWNER",
    subjectType: "LOAD",
    subjectId: "LD-0142",
    summary: "Highveld Logistics posted LD-0142 (JHB → Durban).",
    at: daysFromNow(-2),
  },
  {
    id: "EV-1005",
    eventId: "EVT-20",
    eventType: "MATCH_OFFERED",
    actorId: "SYSTEM",
    actorRole: "SYSTEM",
    subjectType: "MATCH",
    subjectId: "MT-0311",
    summary: "Matching engine generated suggestions for LD-0144.",
    at: daysFromNow(-2),
  },
  {
    id: "EV-1006",
    eventId: "EVT-21",
    eventType: "MATCH_ACCEPTED",
    actorId: "P-OWNER-3",
    actorRole: "FREIGHT_OWNER",
    subjectType: "MATCH",
    subjectId: "MT-0311",
    summary: "Tshwane Structural Steel accepted TR-4410 for LD-0144.",
    at: daysFromNow(-1),
  },
  {
    id: "EV-1007",
    eventId: "EVT-32",
    eventType: "TRIP_STATUS_CHANGED",
    actorId: "P-TRANS-3",
    actorRole: "TRANSPORTER",
    subjectType: "TRIP",
    subjectId: "TP-0058",
    summary: "TP-0058 moved to IN_TRANSIT.",
    at: daysFromNow(0),
  },
];
